In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("Housing.csv")
data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [4]:
data.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [5]:
#cleaning 
data.columns[data.isna().any()]

Index([], dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [7]:
data.select_dtypes(include=["int64"])

price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [8]:
#a=data.select_dtypes(include=["object"])
#a

In [9]:
x=data[["area","bedrooms","bathrooms"]]
x

area  bedrooms  bathrooms
0    7420         4          2
1    8960         4          4
2    9960         3          2
3    7500         4          2
4    7420         4          1
..    ...       ...        ...
540  3000         2          1
541  2400         3          1
542  3620         2          1
543  2910         3          1
544  3850         3          1

[545 rows x 3 columns]

In [10]:
y=data.iloc[:,0]
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

area  bedrooms  bathrooms
126  7160         3          1
363  3584         2          1
370  4280         2          1
31   7000         3          1
113  9620         3          1
..    ...       ...        ...
71   6000         4          2
106  5450         4          2
270  4500         3          2
435  4040         2          1
102  5500         3          2

[381 rows x 3 columns]

In [12]:
import numpy as np 
x=np.array(x).reshape(-1,1)
x

array([[7420],
       [   4],
       [   2],
       ...,
       [3850],
       [   3],
       [   1]])

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [14]:
y_pred=model.predict(x_test)
y_pred

array([6473402.65395882, 6321975.65500429, 3631436.91350162,
       4362326.81524563, 3976018.21338597, 5001221.8106289 ,
       5669832.85230907, 6135382.62733162, 3334276.45053265,
       3507990.48420985, 8871363.1765967 , 3592063.15215823,
       3512572.72831403, 3656570.71569433, 3979732.71917308,
       6658385.46579498, 2873677.73293075, 4733777.39395683,
       4678059.80715015, 4359480.04777558, 4369755.82681985,
       5040224.12139358, 3486199.73722553, 3916586.12079218,
       5569541.19605705, 7607194.65734506, 3278558.86372597,
       5021898.62951507, 7408221.56067752, 3245128.31164196,
       5393349.20822627, 3663999.72726856, 6136250.36564869,
       4962219.49986422, 4653047.78121686, 5616219.555453  ,
       4230833.31038186, 4060584.10817248, 3797721.93560459,
       5317077.00243083, 5469249.53980502, 3479142.17623002,
       6292259.60870739, 4065166.35227666, 4638067.98180899,
       4316763.23122379, 6136250.36564869, 4602901.95309084,
       5120953.73413356,

In [17]:
model.coef_

array([3.71450579e+02, 3.74297346e+05, 1.40247297e+06])

In [18]:
model.intercept_

np.float64(-20291.08854601439)

In [20]:
model.predict([[7160,3,1]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5164660.06526183])

In [21]:
#checking
3.71450579e+02*7160+3.74297346e+05*3+ 1.40247297e+06*1+-20291.08854601439

5164660.065093986