In [37]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [38]:
import numpy as np

In [39]:
a=[1,2,3,4,5,6,7]
type(a)

list

In [40]:
ar=np.array(a)
ar

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
type(ar)

numpy.ndarray

In [42]:
#Dimensions 

In [43]:
np.ndim(a)

1

In [44]:
ar1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
np.ndim(ar1)

2

In [45]:
ar1.shape

(2, 5)

In [46]:
ar1[1][2]

np.int64(8)

In [47]:
ar2=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [48]:
ar2[1][2]

np.int64(7)

In [49]:
ar2=np.arange(1,10,2)
ar2

array([1, 3, 5, 7, 9])

In [50]:
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
ar3.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [52]:
ar3.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
ar4=np.arange(48)
ar4.reshape(2,6,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [54]:
ar3.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [55]:
np.vstack(ar3)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [56]:
np.hstack(ar3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
np.linspace(1,10,5) #seperates into equal parts

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.random.rand(3,2) #generates random valuse in the give matrix size

array([[0.45028123, 0.05167838],
       [0.02736157, 0.84574312],
       [0.66898245, 0.3589366 ]])

In [72]:
np.random.randint(1,5,size=(3,2))

array([[4, 4],
       [3, 3],
       [4, 4]], dtype=int32)

In [73]:
np.random.randint(2,8,5)

array([7, 3, 3, 2, 7], dtype=int32)

In [75]:
a = np.arange(6)
a.reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [77]:
a.transpose()

array([0, 1, 2, 3, 4, 5])